apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-ui2
    name: weather-ui2
    type: web
  name: weather-ui2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-ui2
      name: weather-ui2
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weather-ui2
        name: weather-ui2
        type: web
      name: weather-ui2
    spec:
      containers:
      - image: chinmaydc/weather-ui:1
        imagePullPolicy: IfNotPresent
        name: weather-ui2
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
