apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-ui2
    type: web
  name: weather-ui2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: weather-ui2
    type: web
  type: LoadBalancer
---
